[package]
name = "sse_music_merge"
version = "0.1.0"
authors = ["isavegas <isavegas2006@gmail.com>"]
description = "A tool for merging music mods for Skyrim Special Edition. Note that it will not work for the original Skyrim, currently."

[dependencies]
winreg = "0.4"
byteorder = "1.0.0"